Cleanup workspace warnings
RobotecAI/ROSCon2023Demo pull request #252
Opened 2023-10-18 14:14 UTC by arturkamieniecki

I've cleaned up some warnings form the ros2_ws.

2023-10-20 10:33 UTC, jhanca-robotecai requested changes
Warnings have a meaning and we should either fix the issues or keep the warnings so we know there are issues. Calling `void(variable_name)` hides the warnings, but does not solve the issues. 

What you did in `palletizationNode.cpp` is valid, but the other two changes are not.

2023-10-20 10:33 UTC, jhanca-robotecai commented on ros2_ws/src/blind_path_follower/src/follow_path.cpp
> +        (void)goal;
Just out of curiosity: why not `[maybe_unused]`?

2023-10-30 09:06 UTC, adamdbrw commented
Change (void) to maybe unused for unused parameters and we can merge this.

2023-10-30 13:41 UTC, jhanca-robotecai commented
> Change (void) to maybe unused for unused parameters and we can merge this.

The reason for this parameter to be unused is that it was set fixed within the method. The parameter should be removed completely if not needed and the function calls should be modified accordingly.

Adding `[[maybe_unused]]` is like:
```cpp
int add([[maybe_unused]]int a, [[maybe_unused]]int b) {
    return 2;
}
```

2023-11-07 14:21 UTC, michalpelka approved these changes

2023-11-07 14:21 UTC, merged